//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyz.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoBKEntities : DbContext
    {
        public DemoBKEntities()
            : base("name=DemoBKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Абонент> Абонент { get; set; }
        public virtual DbSet<ВидУслуг> ВидУслуг { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Оборудование> Оборудование { get; set; }
        public virtual DbSet<Порты> Порты { get; set; }
        public virtual DbSet<Порты_В_Оборудовании> Порты_В_Оборудовании { get; set; }
        public virtual DbSet<Районы> Районы { get; set; }
        public virtual DbSet<ТехПерсонал> ТехПерсонал { get; set; }
        public virtual DbSet<ТипОборудования> ТипОборудования { get; set; }
        public virtual DbSet<ТочкаПодключения> ТочкаПодключения { get; set; }
    }
}
