//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абонент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Абонент()
        {
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int ID_Абонента { get; set; }
        public string НомерАбонента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public System.DateTime Дата_Рождения { get; set; }
        public string Номер_телефона { get; set; }
        public string Электорнная_почта { get; set; }
        public string Адрес_проживания { get; set; }
        public int Серия_номер_паспорта { get; set; }
        public string Пароль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
    }
}
